// Hotkeys podem ser agrupadas também em objetos para facilitar o gerenciamento
const hotkeysOld = {
  masterSwitch: hotkeyMasterSwitch,
  switch1: hotkeySwitch1,
  switch2: hotkeySwitch2,
  switch3: hotkeySwitch3,
  switch4: hotkeySwitch4,
  alt1Slots: [
    hotkeyAlt1Slot1,
    hotkeyAlt1Slot2,
    hotkeyAlt1Slot3,
    hotkeyAlt1Slot4,
    hotkeyAlt1Slot5,
    hotkeyAlt1Slot6,
    hotkeyAlt1Slot7,
    hotkeyAlt1Slot8,
    hotkeyAlt1Slot9,
    hotkeyAlt1Slot10,
  ],
  alt2Slots: [
    hotkeyAlt2Slot1,
    hotkeyAlt2Slot2,
    hotkeyAlt2Slot3,
    hotkeyAlt2Slot4,
    hotkeyAlt2Slot5,
    hotkeyAlt2Slot6,
    hotkeyAlt2Slot7,
    hotkeyAlt2Slot8,
    hotkeyAlt2Slot9,
    hotkeyAlt2Slot10,
  ],
  alt3Slots: [
    hotkeyAlt3Slot1,
    hotkeyAlt3Slot2,
    hotkeyAlt3Slot3,
    hotkeyAlt3Slot4,
    hotkeyAlt3Slot5,
    hotkeyAlt3Slot6,
    hotkeyAlt3Slot7,
    hotkeyAlt3Slot8,
    hotkeyAlt3Slot9,
    hotkeyAlt3Slot10,
  ],
  alt4Slots: [
    hotkeyAlt4Slot1,
    hotkeyAlt4Slot2,
    hotkeyAlt4Slot3,
    hotkeyAlt4Slot4,
    hotkeyAlt4Slot5,
    hotkeyAlt4Slot6,
    hotkeyAlt4Slot7,
    hotkeyAlt4Slot8,
    hotkeyAlt4Slot9,
    hotkeyAlt4Slot10,
  ],
};

export { hotkeysOld };
